### ISSUE TITLE
github trending

### ISSUE THREAD

**Issue by zhyongquan** [MLEveryday/100-Days-Of-ML-Code#58]
我们的项目居然上了github trending，哈哈

![image](https://user-images.githubusercontent.com/11530247/44965592-f95ecf80-af68-11e8-9d45-5875d555a73b.png)

**Comment by yyong119** [comment]
有没有兴趣搬运下60_Days_RL_Challenge，地址 https://github.com/andri27-ts/60_Days_RL_Challenge

顺便把组织名字MachineLearning100换成其他的，囊括下更多的搬运项目。

**Comment by zhyongquan** [comment]
名字可以改一下，有什么建议？
这个项目我看到了，作者刚开始，而且都是链接的资源，week1里2个都是youtube的。

**Comment by Huang-Jack** [comment]
@zhyongquan 恭喜啊，我把这个项目也推荐给了热爱ML的同事呢。

https://github.com/andri27-ts/60_Days_RL_Challenge 这个项目我可以帮助翻译下如有需要，刚好最近学习完了莫凡的RL课程

**Comment by zhyongquan** [comment]
@Huang-Jack  可以，我已经开里这个项目，你可以到issue下回复
