### ISSUE TITLE
Error : when open Day 25_Decision_Tree

### ISSUE THREAD

**Issue by smile901122** [MLEveryday/100-Days-Of-ML-Code#79]
![image](https://user-images.githubusercontent.com/11388882/51663070-ad342a80-1ff0-11e9-95e4-39ab2d1f342a.png)

**Comment by smile901122** [comment]
after open, losing some codes.

**Comment by zhyongquan** [comment]
你用什么打开的?这是个notebook

**Comment by smile901122** [comment]
> 你用什么打开的?这是个notebook

jupyter, 我以为是我clone过程中文件损坏了，但是重新下载下来还是打开时报错，打开后就丢失了报错位置之后的一部分代码。
