### ISSUE TITLE
day1:非数值型缺失值填充

### ISSUE THREAD

**Issue by zephyrzoom** [MLEveryday/100-Days-Of-ML-Code#92]
非数值型缺失值怎么填充呀？用Imputer时报错`could not convert string to float`

**Comment by weizy2018** [comment]
> 非数值型缺失值怎么填充呀？用Imputer时报错`could not convert string to float`

新版本的sklearn的Imputer改了，使用
from sklearn.impute import SimpleImputer
impter = SimpleImputer(missing_values=np.nan, strategy='mean')

**Comment by yyong119** [comment]
> > 非数值型缺失值怎么填充呀？用Imputer时报错`could not convert string to float`
> 
> 新版本的sklearn的Imputer改了，使用
> from sklearn.impute import SimpleImputer
> impter = SimpleImputer(missing_values=np.nan, strategy='mean')

感谢提醒，已更新
