### ISSUE TITLE
english translation Issue( 英文翻译时)

### ISSUE THREAD

**Issue by kardam-shashank** [MLEveryday/100-Days-Of-ML-Code#93]
Please provide the english translation.

**Comment by yyong119** [comment]
> Please provide the english translation.

Actually this repo is translated from the english version. See https://github.com/Avik-Jain/100-Days-Of-ML-Code

**Comment by wizardforcel** [comment]
There is no "please provide". You can do it if needed. This is the rule of an open source community.
